version: '3'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-app
    ports:
      - 9000:9000
    volumes:
      - .:/usr/src/app
    tty: true
    command: yarn start
