start:
	docker-compose up -d

stop:
	docker-compose down

connect:
	docker-compose exec mysql "mysql --user=root --password=trex123"

bash:
	docker-compose exec mysql bash

logs:
	docker-compose logs -f
